name: Test pogged.Fetch in Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:

  # No Build Support for Windows and macOS

  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Prepare
      id: prepare
      run: |
        rsync -a --exclude pogged.Fetch/app . pogged.Fetch/app

    - name: Build 
      id: build
      run: |
        docker build pogged.Fetch